#! /bin/sh

xrdb ~/.Xresources
compton &
dunst -conf ~/.config/dunst/dunstrc &
mpd &
polybar main &
nitrogen --set-scaled ~/dotfiles/wallpapers/astronout.jpg &
sxhkd &

devmon --sync --exec-on-drive "notify-send 'Automount' '%l is now mounted at %d.'" --exec-on-remove "notify-send 'Automount' '%l has been removed.'" &
notify-send -a i3 "i3 loaded" "Hello, $USER." &


bspc monitor -d web code term chat music  

bspc config border_width         0
bspc config active_border_color "#3B4B65"
bspc config normal_border_color "#25323C"

bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true

# make second window appear on the right
# bspc config initial_polarity second_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a Shutter state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Pamac-manager state=floating