#!/usr/bin/env sh

# Load the scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

minimize_window() {
  WINDOW_LABEL=$1
  window=$(yabai -m query --windows | jq -r ".[] | select(.app == \"$WINDOW_LABEL\") | .id")

  if [ -z "$window" ]; then
    echo "Window not found: $WINDOW_LABEL"
    return
  fi

  yabai -m window $window --minimize
}

# Make non-resizable windows float, if not floating already

# On window creation, center the window if floating and is the only floating window in the space
yabai -m signal --add event=window_created action='~/.config/yabai/handle_window.sh "$YABAI_WINDOW_ID"'

# Automatically switch back to sub-layer normal
yabai -m signal --add event=application_front_switched action="yabai -m window --sub-layer normal"

# Yabai Indicator - https://github.com/xiamaz/YabaiIndicator
yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'

# AeroIndicator - https://github.com/rien7/AeroIndicator
# yabai -m signal --add event=window_focused action='aeroIndicator focus-change'
# yabai -m signal --add event=window_destroyed action='aeroIndicator focus-change'
# yabai -m signal --add event=space_changed action='aeroIndicator workspace-change $YABAI_SPACE_INDEX'
# yabai -m signal --add event=space_created action='aeroIndicator workspace-created-or-destroyed'
# yabai -m signal --add event=space_destroyed action='aeroIndicator workspace-created-or-destroyed'

# Global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config display_arrangement_order default
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack
yabai -m config window_animation_duration 0.05

# General space settings
yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 15

# Spaces
yabai -m space 1 --label primary
yabai -m space 2 --label browser
yabai -m space 3 --label secondary
yabai -m space 4 --label extra

# Base rules
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add --one-shot app=".*" space=secondary
yabai -m rule --add title="(Copy|Bin|About This Mac|Info)" manage=off
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

# Space rules
yabai -m rule --apply app="^Code$" space=primary
yabai -m rule --apply app="^Arc$" space=browser
yabai -m rule --apply app="^iTerm2$" space=extra

# Scratchpads
yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9
yabai -m rule --add app="^Discord$" title!="^Discord Updater$" scratchpad=discord grid=11:11:1:1:9:9
yabai -m rule --add app="^iTerm2$" scratchpad=term grid=11:11:1:1:9:9
yabai -m rule --add app="^Slack$" scratchpad=slack grid=11:11:1:1:9:9
yabai -m rule --add app="^Linear$" scratchpad=linear grid=11:11:1:1:9:9
yabai -m rule --add app="^BoltAI$" scratchpad=ai grid=11:11:1:1:9:9
yabai -m rule --add app="^Bear$" scratchpad=bear grid=11:11:1:1:9:9

# Floating/unmanaged windows
yabai -m rule --add app="Raycast" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Passwords$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Bitwarden$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Notion$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Toggl Track$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Boop$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Pieces$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Messenger$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Shortcuts$" sub-layer=above manage=off grid=11:11:1:1:9:9
yabai -m rule --add app="^Messages$" sub-layer=above manage=off grid=11:11:1:1:9:9

# System apps / Settings
yabai -m rule --add app="^Settings$" title=".*" sub-layer=above manage=off
yabai -m rule --add app="^System Settings$" sub-layer=above manage=off
yabai -m rule --add app="^About This Mac" sub-layer=above manage=off
yabai -m rule --add app="^App Store$" sub-layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sub-layer=above manage=off
yabai -m rule --add app="^Archive Utility$" sub-layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sub-layer=above manage=off
yabai -m rule --add app="^System Preferences$" sub-layer=above manage=off
yabai -m rule --add app="^System Information$" sub-layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sub-layer=above manage=off
yabai -m rule --add app="^Finder$" manage=off sub-layer=above
yabai -m rule --add app="^Calculator$" sub-layer=above manage=off
yabai -m rule --add app="^Dictionary$" sub-layer=above manage=off
yabai -m rule --add app="^Clock" sub-layer=above manage=off
yabai -m rule --add app="^Contacts" sub-layer=above manage=off
yabai -m rule --add app="^Music$" sub-layer=above manage=off
yabai -m rule --add app="^Preview$" sub-layer=above manage=off
yabai -m rule --add app="^Calendar$" sub-layer=above manage=off
yabai -m rule --add app="^Reminders$" sub-layer=above manage=off
yabai -m rule --add app="^Notes$" sub-layer=above manage=off
yabai -m rule --add app="^Photos$" sub-layer=above manage=off

# Applications
yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off
yabai -m rule --add app='^Arc$' title='^Settings$' manage=off
yabai -m rule --add app='^Arc$' title='^ColorSlurp$' manage=off
yabai -m rule --add app="^Steam$" sub-layer=above manage=off
yabai -m rule --add app="^Bartender 5$" sub-layer=above manage=off
yabai -m rule --add app="^Messenger$" sub-layer=above manage=off
yabai -m rule --add app="^Android Studio$" subrole=AXStandardWindow sub-layer=above manage=off

# Apply rules
yabai -m rule --apply

# Minimize windows/scratcpads
minimize_window "Spotify"
minimize_window "Discord"
minimize_window "Slack"
minimize_window "Linear"
minimize_window "Secretive"
minimize_window "BoltAI"
minimize_window "Bear"

echo "yabai configuration loaded."
